# CI jobs

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: build
      run: docker run --rm -v ${PWD}:/module bitcraze/aideck bash -c "./tools/build/build"

    - name: rename bin file
      run: cp BUILD/GAP8_V2/GCC_RISCV_FREERTOS/target.board.devices.flash.img BUILD/GAP8_V2/GCC_RISCV_FREERTOS/aideck_gap8.bin

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ${{ github.sha }}
        path: BUILD/GAP8_V2/GCC_RISCV_FREERTOS/aideck_gap8.bin
